export const globalConstants = {
  GET_TRAINING_CATEGORIES_IN_PROCESS: 'GET_TRAINING_CATEGORIES_IN_PROCESS',
  GET_TRAINING_CATEGORIES_SUCCESS: 'GET_TRAINING_CATEGORIES_SUCCESS',
  GET_TRAINING_CATEGORIES_FAILURE: 'GET_TRAINING_CATEGORIES_FAILURE',

  GET_EXERCISE_CATEGORIES_IN_PROCESS: 'GET_EXERCISE_CATEGORIES_IN_PROCESS',
  GET_EXERCISE_CATEGORIES_SUCCESS: 'GET_EXERCISE_CATEGORIES_SUCCESS',
  GET_EXERCISE_CATEGORIES_FAILURE: 'GET_EXERCISE_CATEGORIES_FAILURE',

  GET_USER_PROFILE_IN_PROCESS: 'GET_USER_PROFILE_IN_PROCESS',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE'
}
