export const authConstants = {
  REGISTER_IN_PROCESS: 'REGISTER_IN_PROCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_IN_PROCESS: 'LOGIN_IN_PROCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  SOCIAL_LOGIN_IN_PROCESS: 'SOCIAL_LOGIN_IN_PROCESS',
  SOCIAL_LOGIN_SUCCESS: 'SOCIAL_LOGIN_SUCCESS',
  SOCIAL_LOGIN_FAILURE: 'SOCIAL_LOGIN_FAILURE',

  CHANGE_PASSWORD_IN_PROCESS: 'CHANGE_PASSWORD_IN_PROCESS',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  FORGOT_PASSWORD_IN_PROCESS: 'FORGOT_PASSWORD_IN_PROCESS',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  RESET_PASSWORD_IN_PROCESS: 'RESET_PASSWORD_IN_PROCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  LOGOUT: 'LOGOUT',

  GET_PROFILE_IN_PROCESS: 'GET_PROFILE_IN_PROCESS',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

  EDIT_PROFILE_IN_PROCESS: 'EDIT_PROFILE_IN_PROCESS',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',

  CHANGE_AVATAR_IN_PROCESS: 'CHANGE_AVATAR_IN_PROCESS',
  CHANGE_AVATAR_SUCCESS: 'CHANGE_AVATAR_SUCCESS',
  CHANGE_AVATAR_FAILURE: 'CHANGE_AVATAR_FAILURE'
}
