export const globalConstants = {
  GET_TRAINING_CATEGORIES_IN_PROCESS: 'GET_TRAINING_CATEGORIES_IN_PROCESS',
  GET_TRAINING_CATEGORIES_SUCCESS: 'GET_TRAINING_CATEGORIES_SUCCESS',
  GET_TRAINING_CATEGORIES_FAILURE: 'GET_TRAINING_CATEGORIES_FAILURE',

  GET_EXERCISE_CATEGORIES_IN_PROCESS: 'GET_EXERCISE_CATEGORIES_IN_PROCESS',
  GET_EXERCISE_CATEGORIES_SUCCESS: 'GET_EXERCISE_CATEGORIES_SUCCESS',
  GET_EXERCISE_CATEGORIES_FAILURE: 'GET_EXERCISE_CATEGORIES_FAILURE',

  GET_TRAINING_ADVANCEMENT_LEVELS_IN_PROCESS: 'GET_TRAINING_ADVANCEMENT_LEVELS_IN_PROCESS',
  GET_TRAINING_ADVANCEMENT_LEVELS_SUCCESS: 'GET_TRAINING_ADVANCEMENT_LEVELS_SUCCESS',
  GET_TRAINING_ADVANCEMENT_LEVELS_FAILURE: 'GET_TRAINING_ADVANCEMENT_LEVELS_FAILURE',

  GET_USER_PROFILE_IN_PROCESS: 'GET_USER_PROFILE_IN_PROCESS',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

  FOLLOW_USER_IN_PROGRESS: 'FOLLOW_USER_IN_PROGRESS',
  FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',

  SEND_CONTACT_MESSAGE_IN_PROCESS: 'SEND_CONTACT_MESSAGE_IN_PROCESS',
  SEND_CONTACT_MESSAGE_SUCCESS: 'SEND_CONTACT_MESSAGE_SUCCESS',
  SEND_CONTACT_MESSAGE_FAILURE: 'SEND_CONTACT_MESSAGE_FAILURE'
}
