export const trainingsConstants = {
  GET_TRAININGS_IN_PROCESS: 'GET_TRAININGS_IN_PROCESS',
  GET_TRAININGS_SUCCESS: 'GET_TRAININGS_SUCCESS',
  GET_TRAININGS_FAILURE: 'GET_TRAININGS_FAILURE',
  SET_SEARCH: 'SET_SEARCH',
  SET_SORT: 'SET_SORT',
  SET_PAGE: 'SET_PAGE',
  SET_TRAINING_CATEGORY_FILTER: 'SET_TRAINING_CATEGORY_FILTER',
  SET_TRAINING_ADVANCEMENT_LEVEL_FILTER: 'SET_TRAINING_ADVANCEMENT_LEVEL_FILTER'
}
