export const trainingConstants = {
  GET_TRAINING_IN_PROCESS: 'GET_TRAINING_IN_PROCESS',
  GET_TRAINING_SUCCESS: 'GET_TRAINING_SUCCESS',
  GET_TRAINING_AUTH_FAILURE: 'GET_TRAINING_AUTH_FAILURE',
  GET_TRAINING_FAILURE: 'GET_TRAINING_FAILURE',

  REMOVE_TRAINING_IN_PROCESS: 'REMOVE_TRAINING_IN_PROCESS',
  REMOVE_TRAINING_SUCCESS: 'REMOVE_TRAINING_SUCCESS',
  REMOVE_TRAINING_FAILURE: 'REMOVE_TRAINING_FAILURE',

  EDIT_TRAINING_IN_PROCESS: 'EDIT_TRAINING_IN_PROCESS',
  EDIT_TRAINING_SUCCESS: 'EDIT_TRAINING_SUCCESS',
  EDIT_TRAINING_FAILURE: 'EDIT_TRAINING_FAILURE',

  SWITCH_TRAINING_STATUS_IN_PROCESS: 'SWITCH_TRAINING_STATUS_IN_PROCESS',
  SWITCH_TRAINING_STATUS_SUCCESS: 'SWITCH_TRAINING_STATUS_SUCCESS',
  SWITCH_TRAINING_STATUS_FAILURE: 'SWITCH_TRAINING_STATUS_FAILURE',

  CREATE_TRAINING_IN_PROCESS: 'CREATE_TRAINING_IN_PROCESS',
  CREATE_TRAINING_SUCCESS: 'CREATE_TRAINING_SUCCESS',
  CREATE_TRAINING_FAILURE: 'CREATE_TRAINING_FAILURE',

  LIKE_TRAINING_IN_PROCESS: 'LIKE_TRAINING_IN_PROCESS',
  LIKE_TRAINING_SUCCESS: 'LIKE_TRAINING_SUCCESS',
  LIKE_TRAINING_FAILURE: 'LIKE_TRAINING_FAILURE',

  CLONE_TRAINING_IN_PROCESS: 'CLONE_TRAINING_IN_PROCESS',
  CLONE_TRAINING_SUCCESS: 'CLONE_TRAINING_SUCCESS',
  CLONE_TRAINING_FAILURE: 'CLONE_TRAINING_FAILURE',
}
