export const trainingsConstants = {
  GET_TRAININGS_IN_PROCESS: 'GET_TRAININGS_IN_PROCESS',
  GET_TRAININGS_SUCCESS: 'GET_TRAININGS_SUCCESS',
  GET_TRAININGS_FAILURE: 'GET_TRAININGS_FAILURE',
  SET_SEARCH: 'SET_SEARCH'
}
