export const trainingsConstants = {
  GET_TRAININGS_IN_PROCESS: 'GET_TRAININGS_IN_PROCESS',
  GET_TRAININGS_SUCCESS: 'GET_TRAININGS_SUCCESS',
  GET_TRAININGS_FAILURE: 'GET_TRAININGS_FAILURE',

  CREATE_TRAINING_IN_PROCESS: 'CREATE_TRAINING_IN_PROCESS',
  CREATE_TRAINING_SUCCESS: 'CREATE_TRAINING_SUCCESS',
  CREATE_TRAINING_FAILURE: 'CREATE_TRAINING_FAILURE',

  REMOVE_TRAINING_IN_PROCESS: 'REMOVE_TRAINING_IN_PROCESS',
  REMOVE_TRAINING_SUCCESS: 'REMOVE_TRAINING_SUCCESS',
  REMOVE_TRAINING_FAILURE: 'REMOVE_TRAINING_FAILURE',

  SWITCH_TRAINING_STATUS_IN_PROCESS: 'SWITCH_TRAINING_STATUS_IN_PROCESS',
  SWITCH_TRAINING_STATUS_SUCCESS: 'SWITCH_TRAINING_STATUS_SUCCESS',
  SWITCH_TRAINING_STATUS_FAILURE: 'SWITCH_TRAINING_STATUS_FAILURE',

  EDIT_TRAINING_IN_PROCESS: 'EDIT_TRAINING_IN_PROCESS',
  EDIT_TRAINING_SUCCESS: 'EDIT_TRAINING_SUCCESS',
  EDIT_TRAINING_FAILURE: 'EDIT_TRAINING_FAILURE'
};
